[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytorch-md4"
version = "0.1.0"
description = "Word Diffusion Transformer in PyTorch"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0.0",
    "pandas>=2.0.0",
    "pyarrow>=14.0.0",
    "tqdm>=4.66.0",
    "wandb>=0.16.0"
]
