[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytorch-md4"
version = "0.1.0"
description = "Word Diffusion Transformer in PyTorch"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "tqdm>=4.66.0",
    "wandb>=0.23.1",
    "numpy>=2.3.5",
    "onnx>=1.20.0",
    "onnxconverter-common>=1.16.0",
    "onnxruntime>=1.23.2",
    "safetensors>=0.7.0",
    "scipy>=1.16.3"
]
